name: Examples

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-examples
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  examples:
    name: Build and run examples on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false

    - name: Setup Java
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@8379f6a1328ee0e06e2bb424dadb7b159856a326 # v4.4.0

    - name: run examples against released sigstore
      working-directory: examples/hello-world
      shell: bash
      run: ./test.sh

    - name: install sigstore java development jars into mavenLocal
      run: ./gradlew publishToMavenLocal -Prelease -PskipSigning

    - name: calculate development version
      id: dev_version
      shell: bash
      run: |
        set -Exeo pipefail
        echo "version=$(grep "^version=" gradle.properties | cut -d'=' -f2)" >> $GITHUB_OUTPUT

    - name: run examples against development version
      working-directory: examples/hello-world
      shell: bash
      env:
        VERSION: ${{ steps.dev_version.outputs.version }}
      run: ./test.sh -Dsigstore.version=${VERSION}
